In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("akyshnik/lyrics")

print("Path to dataset files:", path)

Downloading to /home/alberto/.cache/kagglehub/datasets/akyshnik/lyrics/1.archive...

100%|██████████████████████████████████████| 90.0M/90.0M [00:04<00:00, 22.6MB/s]

Extracting files...

Path to dataset files: /home/alberto/.cache/kagglehub/datasets/akyshnik/lyrics/versions/1

In [3]:
import os

print(os.listdir(path))

['kaggle_clean.csv']

In [4]:
import pandas as pd

file_path = os.path.join(path, "kaggle_clean.csv")
df = pd.read_csv(file_path)

In [5]:
df.head()

,Unnamed: 0,index,song,year,artist,genre,lyrics,wnum
0,0,0,ego-remix,2009,beyonce-knowles,Pop,oh baby how you doing?\nyou know i'm gonna cut...,433
1,1,1,then-tell-me,2009,beyonce-knowles,Pop,playin' everything so easy\nit's like you seem...,258
2,2,2,honesty,2009,beyonce-knowles,Pop,if you search\nfor tenderness\nit isn't hard t...,170
3,3,3,you-are-my-rock,2009,beyonce-knowles,Pop,oh oh oh i oh oh oh i\nverse 1:\nif i wrote a ...,522
4,4,4,black-culture,2009,beyonce-knowles,Pop,party the people the people the party it's pop...,312

In [6]:
print(df.columns)

Index(['Unnamed: 0', 'index', 'song', 'year', 'artist', 'genre', 'lyrics',
       'wnum'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266557 entries, 0 to 266556
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  266557 non-null  int64
 1   index       266557 non-null  int64
 2   song        266556 non-null  object
 3   year        266557 non-null  int64
 4   artist      266557 non-null  object
 5   genre       266557 non-null  object
 6   lyrics      266535 non-null  object
 7   wnum        266557 non-null  int64
dtypes: int64(4), object(4)
memory usage: 16.3+ MB

In [8]:
df["genre"].unique()

array(['Pop', 'Hip-Hop', 'Not Available', 'Rock', 'Metal', 'Other',
       'Country', 'Jazz', 'Electronic', 'Folk', 'R&B', 'Indie'],
      dtype=object)

In [10]:
df[df["artist"] == "demonaz"]

,Unnamed: 0,index,song,year,artist,genre,lyrics,wnum
361,361,415,northern-hymn,2011,demonaz,Metal,gods of the mountains\nsky forest and seas\nla...,58
362,362,416,under-the-great-fires,2011,demonaz,Metal,rise gods of the fierous black burning skies\n...,226
363,363,417,all-blackened-sky,2011,demonaz,Metal,a dying skyline cold from wind and rain\nautum...,109
364,364,418,legends-of-fire-and-ice,2011,demonaz,Metal,fiends of the gods to war we ride\nover the bl...,48
365,365,419,ode-to-battle,2011,demonaz,Metal,cold is the winter\non its ground we ride\nto ...,29
366,366,420,dying-sun,2011,demonaz,Metal,instrumental,1
367,367,421,over-the-mountains,2011,demonaz,Metal,over the mountains again\nwandering above the ...,139
368,368,422,march-of-the-norse,2011,demonaz,Metal,dethroned worlds on fire under the ice\nall wh...,169
369,369,423,where-gods-once-rode,2011,demonaz,Metal,once shadows called i saddled my horse\nto the...,158
370,370,424,a-son-of-the-sword,2011,demonaz,Metal,i rode for the moments once under red sky\nbor...,49